import { useState } from 'react';
import { Activity, ChevronDown, CircleUserRound, Cloud, Fingerprint as FingerprintIcon, Gauge, Settings, Shield, ShieldCheck, Sparkles, Waves } from 'lucide-react';
import type { ConnectionStatus, Score } from '../ws/socketClient';
import { ActivityTimeline } from './ActivityTimeline';
import { AdminDashboard } from './AdminDashboard';
import { BehavioralHeartbeat } from './BehavioralHeartbeat';
import { DriftTimeline } from './DriftTimeline';
import { ExplainabilityPanel } from './ExplainabilityPanel';
import { LiveSignalPanel } from './LiveSignalPanel';
import { PassiveChallenge } from './PassiveChallenge';
import { TrustScoreGauge } from './TrustScoreGauge';
import { deltaPercent, metricLabels, patternPercentages, type DerivedMetrics, type MetricKey, type MetricsBaseline } from '../metrics/derivedMetrics';

type Page = 'overview' | 'live' | 'fingerprint' | 'security' | 'insights' | 'aws' | 'settings';
type Props = { score: Score; vector: Record<string, number>; metrics: DerivedMetrics | null; baseline: MetricsBaseline | null; connection: ConnectionStatus; locked: boolean; onReset: () => void; onRecalibrate: () => void; page?: Page };
const nav = [{ id: 'overview', label: 'Overview', icon: Gauge }, { id: 'live', label: 'Live Rhythm', icon: Waves }, { id: 'fingerprint', label: 'My Fingerprint', icon: FingerprintIcon }, { id: 'security', label: 'Security', icon: Shield }, { id: 'insights', label: 'Insights', icon: Sparkles }] as const;
const pct = (value: number | undefined) => Math.round(Math.max(0, Math.min(1, value || 0)) * 100);
const metricValue = (metrics: DerivedMetrics | null, key: MetricKey, digits = 1) => metrics ? `${metrics[key].toFixed(digits)} ${metricLabels[key]}` : 'Not enough data yet';
const metricDelta = (metrics: DerivedMetrics | null, baseline: MetricsBaseline | null, key: MetricKey) => { const delta = metrics && baseline ? deltaPercent(metrics[key], baseline[key]) : null; return delta === null ? 'Baseline pending' : `${delta >= 0 ? '+' : ''}${delta.toFixed(1)}% vs baseline`; };
const baselineValue = (baseline: MetricsBaseline | null, key: MetricKey) => baseline ? `${baseline[key].mean.toFixed(1)} ${metricLabels[key]} · ±${baseline[key].std.toFixed(1)}` : 'Not enough data yet';

function Header({ connection, setPage }: { connection: ConnectionStatus; setPage: (page: Page) => void }) { return <header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={18} /></span><div><b>DBLA</b><small>DIGITAL BODY LANGUAGE ANALYZER</small></div></div><div className="topbar-actions"><button className="system-status" onClick={() => setPage('aws')}><span className={connection === 'connected' ? '' : 'offline'} /> SYSTEM ONLINE</button><button className="user-chip"><CircleUserRound size={18} /><span>Kritika</span><ChevronDown size={14} /></button></div></header>; }
function Sidebar({ page, setPage }: { page: Page; setPage: (page: Page) => void }) { return <aside className="sidebar"><nav>{nav.map(({ id, label, icon: Icon }) => <button className={page === id ? 'active' : ''} key={id} onClick={() => setPage(id)}><Icon size={16} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className={page === 'aws' ? 'active' : ''} onClick={() => setPage('aws')}><Cloud size={16} /><span>AWS Status</span></button><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}><Settings size={16} /><span>Settings</span></button></div></aside>; }
function Footer({ onReset }: { onReset: () => void }) { return <footer><span><ShieldCheck size={14} /> VECTOR-ONLY PRIVACY</span><span><Shield size={14} /> DERIVED SIGNALS ONLY</span><button className="demo-reset" onClick={onReset}>Reset demo</button></footer>; }
function Overview({ score, vector, connection, locked }: Props) { return <><section className="hero"><div><div className="eyebrow">CONTINUOUS BEHAVIORAL VERIFICATION</div><h1>Behavior is<br /><em>a signal.</em></h1><p className="lede">DBLA looks for meaningful changes in timing and motion. A behavioral anomaly recommends verification; it does not claim perfect identity.</p></div><TrustScoreGauge score={locked ? 0 : score.trust_score} tier={locked ? 'lock' : score.tier} /></section><PassiveChallenge active={score.tier === 'challenge'} /><section className="overview-grid"><BehavioralHeartbeat anomaly={score.tier !== 'silent'} /><LiveSignalPanel vector={vector} tier={locked ? 'lock' : score.tier} trust={score.trust_score} connection={connection} /><ExplainabilityPanel reasons={score.reasons} bot={score.bot_probability} /><DriftTimeline score={score.trust_score} /><div className="panel activity-panel"><div className="panel-title"><span>Recent activity</span><small>LIVE STREAM</small></div><ActivityTimeline vector={vector} /></div></section><AdminDashboard /></>; }
function StatTile({ label, value, sub }: { label: string; value: string; sub: string }) { return <div className="stat-tile"><small>{label}</small><strong>{value}</strong><span>{sub}</span><i className="sparkline">⌁⌁⌁⌁</i></div>; }
function LiveRhythm({ score, vector, connection, metrics, baseline }: Props) { return <><div className="page-heading"><div><div className="eyebrow">LIVE RHYTHM</div><h2>Good evening, Kritika</h2><p>Your digital rhythm is consistent.</p></div><span className="status-badge">{connection === 'connected' ? 'LISTENING' : 'RECONNECTING'}</span></div><div className="live-layout"><div className="live-main"><section className="panel greeting-card"><div><h3>Authenticity Score</h3><p>Behavior matches your learned profile.</p></div><TrustScoreGauge score={score.trust_score} tier={score.tier} /></section><div className="stats-row"><StatTile label="Typing" value={metricValue(metrics, 'typing_wpm')} sub={metricDelta(metrics, baseline, 'typing_wpm')} /><StatTile label="Mouse" value={metricValue(metrics, 'mouse_velocity_px_ms')} sub={metricDelta(metrics, baseline, 'mouse_velocity_px_ms')} /><StatTile label="Scroll" value={metricValue(metrics, 'scroll_speed_px_ms')} sub={metricDelta(metrics, baseline, 'scroll_speed_px_ms')} /><StatTile label="Session" value={metricValue(metrics, 'active_minutes')} sub={metricDelta(metrics, baseline, 'active_minutes')} /></div><div className="live-bottom"><DriftTimeline score={score.trust_score} /><div className="panel"><div className="panel-title"><span>Recent activity</span><small>NOW</small></div><ActivityTimeline vector={vector} /></div></div></div><section className="panel rhythm-panel"><div className="panel-title"><span>LIVE RHYTHM</span><small>LISTENING</small></div><p>Derived signals update every 1.5 seconds.</p><div className="match-gauge"><strong>{metricValue(metrics, 'typing_wpm')}</strong><span>BEHAVIORAL MATCH</span></div></section></div></>; }
function Insights({ vector, metrics, baseline }: Props) { const patterns = metrics ? patternPercentages(metrics) : null; const style = patterns ? Object.entries(patterns).sort(([, a], [, b]) => b - a)[0][0].toUpperCase() : 'COLLECTING'; return <><div className="page-heading"><div><div className="eyebrow">LIVE INSIGHTS</div><h2>Real-time analysis of your digital body language.</h2></div></div><div className="stats-row insight-stats"><StatTile label="Typing WPM" value={metricValue(metrics, 'typing_wpm')} sub={metricDelta(metrics, baseline, 'typing_wpm')} /><StatTile label="Mouse px/ms" value={metricValue(metrics, 'mouse_velocity_px_ms')} sub={metricDelta(metrics, baseline, 'mouse_velocity_px_ms')} /><StatTile label="Scroll px/ms" value={metricValue(metrics, 'scroll_speed_px_ms')} sub={metricDelta(metrics, baseline, 'scroll_speed_px_ms')} /><StatTile label="Session" value={metricValue(metrics, 'active_minutes')} sub={metricDelta(metrics, baseline, 'active_minutes')} /></div><div className="insight-middle"><div className="panel"><div className="panel-title"><span>Last event</span><small>LIVE</small></div><ActivityTimeline vector={vector} /></div><div className="panel pattern-panel"><div className="panel-title"><span>Behavior pattern</span><small>CURRENT STYLE</small></div><strong className="style-badge">{style}</strong><div className="pattern-chips"><span>Focused {patterns?.focused ?? 0}%</span><span>Exploratory {patterns?.exploratory ?? 0}%</span><span>Idle {patterns?.idle ?? 0}%</span><span>Erratic {patterns?.erratic ?? 0}%</span></div></div></div><div className="insight-bottom"><div className="panel rhythm-behavior"><div className="panel-title"><span>How your rhythm behaves</span><small>DERIVED SIGNALS</small></div><p><i />Typing <strong>{metricValue(metrics, 'key_flight_ms')}</strong></p><p><i />Mouse <strong>{metricValue(metrics, 'mouse_curvature')}</strong></p><p><i />Scroll <strong>{metricValue(metrics, 'scroll_reversals')}</strong></p></div><div className="panel recommendations"><div className="panel-title"><span>Insights &amp; recommendations</span><small>LIVE</small></div><p>{metrics ? `${metricDelta(metrics, baseline, 'typing_wpm')} typing signal` : 'Not enough data yet'}</p></div></div></>; }
function Fingerprint({ baseline, onRecalibrate }: Props) { const groups: [string, string, MetricKey[]][] = [['Typing', 'WPM · Flight · Dwell · Digraph', ['typing_wpm', 'key_flight_ms', 'key_dwell_ms', 'digraph_ms']], ['Mouse', 'Velocity · Acceleration · Curvature', ['mouse_velocity_px_ms', 'mouse_acceleration', 'mouse_curvature']], ['Scroll', 'Speed · Reversals', ['scroll_speed_px_ms', 'scroll_reversals']]]; return <><div className="page-heading"><div><div className="eyebrow">MY FINGERPRINT</div><h2>Your learned behavioral baseline.</h2></div><button className="outline-button" onClick={onRecalibrate}>Re-calibrate</button></div><section className="fingerprint-grid">{groups.map(([name, detail, keys]) => <div className="panel" key={name}><div className="panel-title"><span>{name}</span><small>BASELINE</small></div><p>{detail}</p>{keys.map((key) => <div className="baseline-metric" key={key}><span>{metricLabels[key]}</span><strong>{baselineValue(baseline, key)}</strong></div>)}</div>)}</section><div className="panel baseline-note"><b>{baseline ? '30 / 30 samples collected' : 'Not enough data yet'}</b><span>Derived means and standard deviations only. Raw input is never stored.</span></div></>; }
function SimplePage({ page, onReset, onRecalibrate, baseline }: Props) { if (page === 'fingerprint') return <Fingerprint baseline={baseline} onRecalibrate={onRecalibrate} score={{} as Score} vector={{}} metrics={null} connection="disconnected" locked={false} onReset={onReset} />; if (page === 'aws') return <><div className="page-heading"><div><div className="eyebrow">AWS STATUS</div><h2>Infrastructure readiness.</h2></div><span className="status-badge warning">NOT CONFIGURED</span></div><section className="panel service-list">{['S3 training archive', 'Lambda scoring', 'API Gateway', 'CloudWatch alerts'].map((service) => <div key={service}><Cloud size={16} /><span>{service}</span><strong>NOT CONFIGURED</strong></div>)}</section></>; return <><div className="page-heading"><div><div className="eyebrow">SETTINGS</div><h2>Privacy and session controls.</h2></div></div><section className="settings-grid"><div className="panel"><h3>Privacy note</h3><p>Vector-only privacy. Derived signals only. No text is recorded.</p><label>Sampling interval <strong>1.5s</strong></label></div><div className="panel"><h3>Demo controls</h3><p>Reset the current session and return to calibration.</p><button className="outline-button" onClick={onReset}>Reset demo</button></div></section></>; }
export function DashboardShell(props: Props) { const [page, setPage] = useState<Page>('overview'); const content = page === 'overview' ? <Overview {...props} /> : page === 'live' ? <LiveRhythm {...props} /> : page === 'security' ? <Overview {...props} /> : page === 'insights' ? <Insights {...props} /> : <SimplePage {...props} page={page as 'fingerprint' | 'aws' | 'settings'} />; return <div className="dashboard-frame"><Header connection={props.connection} setPage={setPage} /><div className="dashboard-body"><Sidebar page={page} setPage={setPage} /><main className="dashboard-main">{content}<Footer onReset={props.onReset} /></main></div></div>; }
