import { useState } from 'react';
import { Activity, BarChart3, ChevronDown, CircleUserRound, Cloud, Fingerprint, Gauge, Settings, Shield, ShieldCheck, Sparkles, Waves, Wifi } from 'lucide-react';
import type { ConnectionStatus, Score } from '../ws/socketClient';
import { ActivityTimeline } from './ActivityTimeline';
import { AdminDashboard } from './AdminDashboard';
import { BehavioralHeartbeat } from './BehavioralHeartbeat';
import { DriftTimeline } from './DriftTimeline';
import { ExplainabilityPanel } from './ExplainabilityPanel';
import { LiveSignalPanel } from './LiveSignalPanel';
import { PassiveChallenge } from './PassiveChallenge';
import { TrustScoreGauge } from './TrustScoreGauge';
import { PLACEHOLDER_DEVIATION_PERCENT, UNAVAILABLE_METRIC } from '../mocks/dashboardMock';

type Page = 'overview' | 'live' | 'fingerprint' | 'security' | 'insights' | 'aws' | 'settings';
type Props = { score: Score; vector: Record<string, number>; connection: ConnectionStatus; locked: boolean; onReset: () => void; onRecalibrate: () => void };
const nav = [{ id: 'overview', label: 'Overview', icon: Gauge }, { id: 'live', label: 'Live Rhythm', icon: Waves }, { id: 'fingerprint', label: 'My Fingerprint', icon: Fingerprint }, { id: 'security', label: 'Security', icon: Shield }, { id: 'insights', label: 'Insights', icon: Sparkles } ] as const;
const pct = (value: number | undefined) => Math.round(Math.max(0, Math.min(1, value || 0)) * 100);
const signalLabel = (value: number | undefined) => value === undefined ? '--' : `${pct(value)}%`;

function Header({ connection, page, setPage }: { connection: ConnectionStatus; page: Page; setPage: (page: Page) => void }) {
  return <header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={18} /></span><div><b>DBLA</b><small>DIGITAL BODY LANGUAGE ANALYZER</small></div></div><div className="topbar-actions"><button className="system-status" onClick={() => setPage('aws')}><span className={connection === 'connected' ? '' : 'offline'} /> SYSTEM ONLINE</button><button className="user-chip"><CircleUserRound size={18} /><span>Kritika</span><ChevronDown size={14} /></button></div></header>;
}

function Sidebar({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  return <aside className="sidebar"><nav>{nav.map(({ id, label, icon: Icon }) => <button className={page === id ? 'active' : ''} key={id} onClick={() => setPage(id)}><Icon size={16} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className={page === 'aws' ? 'active' : ''} onClick={() => setPage('aws')}><Cloud size={16} /><span>AWS Status</span></button><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}><Settings size={16} /><span>Settings</span></button></div></aside>;
}

function Footer({ onReset }: { onReset: () => void }) { return <footer><span><ShieldCheck size={14} /> VECTOR-ONLY PRIVACY</span><span><Shield size={14} /> DERIVED SIGNALS ONLY</span><button className="demo-reset" onClick={onReset}>Reset demo</button></footer>; }

function Overview({ score, vector, connection, locked, onReset }: Props) {
  return <><section className="hero"><div><div className="eyebrow">CONTINUOUS BEHAVIORAL VERIFICATION</div><h1>Behavior is<br /><em>a signal.</em></h1><p className="lede">DBLA looks for meaningful changes in timing and motion. A behavioral anomaly recommends verification; it does not claim perfect identity.</p></div><TrustScoreGauge score={locked ? 0 : score.trust_score} tier={locked ? 'lock' : score.tier} /></section><PassiveChallenge active={score.tier === 'challenge'} /><section className="overview-grid"><BehavioralHeartbeat anomaly={score.tier !== 'silent'} /><LiveSignalPanel vector={vector} tier={locked ? 'lock' : score.tier} trust={score.trust_score} connection={connection} /><ExplainabilityPanel reasons={score.reasons} bot={score.bot_probability} /><DriftTimeline score={score.trust_score} /><div className="panel activity-panel"><div className="panel-title"><span>Recent activity</span><small>LIVE STREAM</small></div><ActivityTimeline vector={vector} /></div></section><AdminDashboard /></>;
}

function StatTile({ label, value, sub = 'CONSISTENT' }: { label: string; value: string; sub?: string }) { return <div className="stat-tile"><small>{label}</small><strong>{value}</strong><span>{sub}</span><i className="sparkline">⌁⌁⌁⌁</i></div>; }
function LiveRhythm({ score, vector, connection }: Props) { const hour = new Date().getHours(); const greeting = hour < 12 ? 'Morning' : hour < 18 ? 'Afternoon' : 'Evening'; return <><div className="page-heading"><div><div className="eyebrow">LIVE RHYTHM</div><h2>Good {greeting}, Kritika</h2><p>Your digital rhythm is consistent.</p></div><span className="status-badge">{connection === 'connected' ? 'LISTENING' : 'RECONNECTING'}</span></div><div className="live-layout"><div className="live-main"><section className="panel greeting-card"><div><h3>Authenticity Score</h3><p>Behavior matches your learned profile.</p></div><TrustScoreGauge score={score.trust_score} tier={score.tier} /><span className="secure-badge">SECURE</span></section><div className="stats-row"><StatTile label="Typing" value={signalLabel(vector.typing_speed)} /><StatTile label="Mouse" value={signalLabel(vector.mouse_velocity)} /><StatTile label="Scroll" value={signalLabel(vector.scroll_speed)} /><StatTile label="Session" value={UNAVAILABLE_METRIC} sub="ACTIVE" /></div><div className="live-bottom"><DriftTimeline score={score.trust_score} /><div className="panel"><div className="panel-title"><span>Recent activity</span><small>NOW</small></div><ActivityTimeline vector={vector} /></div></div></div><LiveRhythmPanel vector={vector} /></div></>; }
function LiveRhythmPanel({ vector }: { vector: Record<string, number> }) { return <section className="panel rhythm-panel"><div className="panel-title"><span>LIVE RHYTHM</span><small className="listening">LISTENING</small></div><p>Your interactions are being continuously observed.</p><div className="match-gauge"><strong>{pct(vector.typing_speed || vector.mouse_velocity || vector.scroll_speed)}%</strong><span>BEHAVIORAL MATCH</span></div><div className="mini-stats"><StatTile label="Typing WPM" value={UNAVAILABLE_METRIC} sub="DERIVED" /><StatTile label="Mouse px/ms" value={UNAVAILABLE_METRIC} sub="DERIVED" /><StatTile label="Scroll px/ms" value={UNAVAILABLE_METRIC} sub="DERIVED" /></div><div className="last-events"><b>Last event</b><ActivityTimeline vector={vector} compact /></div></section>; }

function Security({ score, vector }: Props) { const risk = score.tier === 'challenge' || score.tier === 'lock'; const deviation = risk ? 46 : PLACEHOLDER_DEVIATION_PERCENT; return <><div className="page-heading security-heading"><div><div className="eyebrow"><Shield size={14} /> SECURITY</div><h2>Monitor, detect, and stay protected.</h2></div><div className={`security-status ${risk ? 'risk' : ''}`}><strong>{risk ? 'Review recommended' : 'No active threats'}</strong><small>Last scan {new Date().toLocaleTimeString()}</small></div></div><div className="security-layout"><div className="panel timeline-panel"><div className="panel-title"><span>Security timeline</span><small>SESSION</small></div><ActivityTimeline vector={vector} /></div><section className={`panel anomaly-card ${risk ? 'risk' : 'calm'}`}><div className="panel-title"><span>Behavioral anomaly</span><small>{risk ? 'ELEVATED' : 'MONITORING'}</small></div><strong className="confidence">{Math.round(score.trust_score)}%</strong><span className="confidence-label">IDENTITY CONFIDENCE</span>{['Typing', 'Mouse', 'Scroll'].map((label) => <div className="deviation" key={label}><span>{label}</span><i><b style={{ width: `${deviation}%` }} /></i><strong>{deviation}%</strong></div>)}<div className="primary-anomaly"><small>PRIMARY ANOMALY</small><span>{risk ? score.reasons[0]?.reason || 'Behavioral deviation detected' : 'No meaningful behavioral anomaly detected.'}</span></div>{risk && <button className="verify-button">VERIFY IDENTITY</button>}</section><div className="security-stack"><div className="panel"><div className="panel-title"><span>Recent alerts</span><small>3 ITEMS</small></div><p className="alert-row high">High <span>{risk ? 'Review recommended' : 'No active threat'}</span></p><p className="alert-row medium">Medium <span>Signal deviation watch</span></p><p className="alert-row normal">Normal <span>Session observed</span></p></div><div className="panel donut-panel"><div className="panel-title"><span>Threat distribution</span><small>SESSION</small></div><div className="donut"><strong>{risk ? '1' : '0'}</strong><span>EVENTS</span></div><small>Behavioral · Typing · Mouse · Scroll</small></div><div className="panel"><div className="panel-title"><span>Recent activity</span></div><ActivityTimeline vector={vector} compact /></div></div></div><div className="panel security-chart"><div className="panel-title"><span>Security activity</span><small>LAST 18 MIN · %</small></div><div className="series"><span className="mint-line" /> Normal <span className="amber-line" /> Anomaly <span className="red-line" /> Threat</div><DriftTimeline score={score.trust_score} /></div></>; }

function Insights({ score, vector }: Props) { const focused = Math.max(pct(vector.typing_speed), pct(vector.mouse_velocity)); return <><div className="page-heading"><div><div className="eyebrow">LIVE INSIGHTS</div><h2>Real-time analysis of your digital body language.</h2></div><select defaultValue="live" aria-label="Insight range"><option value="live">LIVE</option><option value="hour">LAST HOUR</option><option value="today">TODAY</option></select></div><div className="stats-row insight-stats"><StatTile label="Typing WPM" value={UNAVAILABLE_METRIC} sub={`${signalLabel(vector.typing_speed)} delta`} /><StatTile label="Mouse px/ms" value={UNAVAILABLE_METRIC} sub={`${signalLabel(vector.mouse_velocity)} delta`} /><StatTile label="Scroll px/ms" value={UNAVAILABLE_METRIC} sub={`${signalLabel(vector.scroll_speed)} delta`} /><StatTile label="Session" value={UNAVAILABLE_METRIC} sub="ACTIVE" /></div><div className="insight-middle"><div className="panel"><div className="panel-title"><span>Last event</span><small>LIVE</small></div><ActivityTimeline vector={vector} /></div><div className="panel pattern-panel"><div className="panel-title"><span>Behavior pattern</span><small>CURRENT STYLE</small></div><strong className="style-badge">FOCUSED</strong><div className="pattern-chips"><span>Focused {focused}%</span><span>Exploratory {Math.max(0, 100 - focused)}%</span><span>Idle {score.trust_score < 50 ? 40 : 8}%</span><span>Erratic {score.tier === 'challenge' ? 30 : 2}%</span></div></div></div><div className="insight-bottom"><div className="panel rhythm-behavior"><div className="panel-title"><span>How your rhythm behaves</span><small>DERIVED SIGNALS</small></div><p><i />Typing <strong>Steady and rhythmic</strong></p><p><i />Mouse <strong>Smooth movement</strong></p><p><i />Scroll <strong>Periodic bursts</strong></p><div className="small-donut">{score.trust_score}%</div></div><div className="panel recommendations"><div className="panel-title"><span>Insights &amp; recommendations</span><small>LIVE</small></div>{['You\'re in a focused state!', 'Try a short break', 'Great rhythm!'].map((text) => <button key={text}>{text}<span>↗</span></button>)}</div></div></>; }

function SimplePage({ page, onReset, onRecalibrate }: { page: 'fingerprint' | 'aws' | 'settings'; onReset: () => void; onRecalibrate: () => void }) { if (page === 'fingerprint') return <><div className="page-heading"><div><div className="eyebrow">MY FINGERPRINT</div><h2>Your learned behavioral baseline.</h2></div><button className="outline-button" onClick={onRecalibrate}>Re-calibrate</button></div><section className="fingerprint-grid">{[['Typing', 'Key flight time · Dwell · Digraph latency'], ['Mouse', 'Velocity · Acceleration · Path curvature'], ['Scroll', 'Speed · Reversals']].map(([name, detail]) => <div className="panel" key={name}><div className="panel-title"><span>{name}</span><small>BASELINE</small></div><p>{detail}</p><strong>--</strong><small>Awaiting detailed baseline metrics</small></div>)}</section><div className="panel baseline-note"><b>30 / 30 samples collected</b><span>Last updated from the calibration session. Raw input is never stored.</span></div></>; if (page === 'aws') return <><div className="page-heading"><div><div className="eyebrow">AWS STATUS</div><h2>Infrastructure readiness.</h2></div><span className="status-badge warning">NOT CONFIGURED</span></div><section className="panel service-list">{['S3 training archive', 'Lambda scoring', 'API Gateway', 'CloudWatch alerts'].map((service) => <div key={service}><Cloud size={16} /><span>{service}</span><strong>NOT CONFIGURED</strong></div>)}</section></>; return <><div className="page-heading"><div><div className="eyebrow">SETTINGS</div><h2>Privacy and session controls.</h2></div></div><section className="settings-grid"><div className="panel"><h3>Privacy note</h3><p>Vector-only privacy. Derived signals only. No text is recorded.</p><label>Sampling interval <strong>1.25s</strong></label><label>Browser notifications <input type="checkbox" defaultChecked /></label><label>Security alerts <input type="checkbox" defaultChecked /></label></div><div className="panel"><h3>Demo controls</h3><p>Reset the current session and return to calibration.</p><button className="outline-button" onClick={onReset}>Reset demo</button></div></section></>; }

export function DashboardShell(props: Props) { const [page, setPage] = useState<Page>('overview'); const content = page === 'overview' ? <Overview {...props} /> : page === 'live' ? <LiveRhythm {...props} /> : page === 'security' ? <Security {...props} /> : page === 'insights' ? <Insights {...props} /> : <SimplePage page={page} onReset={props.onReset} onRecalibrate={props.onRecalibrate} />; return <div className="dashboard-frame"><Header connection={props.connection} page={page} setPage={setPage} /><div className="dashboard-body"><Sidebar page={page} setPage={setPage} /><main className="dashboard-main">{content}<Footer onReset={props.onReset} /></main></div></div>; }