import { useState } from 'react';
import { Activity, ChevronDown, CircleUserRound, Cloud, Fingerprint as FingerprintIcon, Gauge, Settings, Shield, ShieldCheck, Sparkles, Waves } from 'lucide-react';
import type { User } from '../auth/AuthProvider';
import type { ConnectionStatus, Score } from '../ws/socketClient';
import { loadCalibrationProgress, CALIBRATION_MINIMUM, type Behavior } from '../metrics/calibrationProgress';
import { deltaPercent, metricLabels, patternPercentages, type DerivedMetrics, type MetricKey, type MetricsBaseline } from '../metrics/derivedMetrics';
import { ActivityTimeline } from './ActivityTimeline';
import { AdminDashboard } from './AdminDashboard';
import { BehavioralHeartbeat } from './BehavioralHeartbeat';
import { DriftTimeline } from './DriftTimeline';
import { ExplainabilityPanel } from './ExplainabilityPanel';
import { LiveSignalPanel } from './LiveSignalPanel';
import { PassiveChallenge } from './PassiveChallenge';
import { TrustScoreGauge } from './TrustScoreGauge';

type Page = 'overview' | 'live' | 'fingerprint' | 'security' | 'insights' | 'aws' | 'settings';
type Props = { user: User; onLogout: () => void; score: Score; vector: Record<string, number>; metrics: DerivedMetrics | null; baseline: MetricsBaseline | null; connection: ConnectionStatus; locked: boolean; onReset: () => void; onRecalibrate: () => void };
const nav = [{ id: 'overview', label: 'Overview', icon: Gauge }, { id: 'live', label: 'Live Rhythm', icon: Waves }, { id: 'fingerprint', label: 'My Fingerprint', icon: FingerprintIcon }, { id: 'security', label: 'Security', icon: Shield }, { id: 'insights', label: 'Insights', icon: Sparkles }] as const;
const metricValue = (metrics: DerivedMetrics | null, key: MetricKey) => metrics ? `${metrics[key].toFixed(1)} ${metricLabels[key]}` : 'Not enough data yet';
const metricDelta = (metrics: DerivedMetrics | null, baseline: MetricsBaseline | null, key: MetricKey) => { const delta = metrics && baseline ? deltaPercent(metrics[key], baseline[key]) : null; return delta === null ? 'Baseline pending' : `${delta >= 0 ? '+' : ''}${delta.toFixed(1)}% vs baseline`; };
function Header({ user, onLogout, connection, setPage }: { user: User; onLogout: () => void; connection: ConnectionStatus; setPage: (page: Page) => void }) { const name = String(user.user_metadata?.display_name || user.email?.split('@')[0] || 'Account'); return <header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={18} /></span><div><b>DBLA</b><small>DIGITAL BODY LANGUAGE ANALYZER</small></div></div><div className="topbar-actions"><button className="system-status" onClick={() => setPage('aws')}><span className={connection === 'connected' ? '' : 'offline'} /> SYSTEM ONLINE</button><details className="user-menu"><summary className="user-chip"><CircleUserRound size={18} /><span>{name}</span><ChevronDown size={14} /></summary><div className="user-menu-panel"><small>{user.email}</small><button onClick={onLogout}>Log out</button></div></details></div></header>; }
function Sidebar({ page, setPage }: { page: Page; setPage: (page: Page) => void }) { return <aside className="sidebar"><nav>{nav.map(({ id, label, icon: Icon }) => <button className={page === id ? 'active' : ''} key={id} onClick={() => setPage(id)}><Icon size={16} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className={page === 'aws' ? 'active' : ''} onClick={() => setPage('aws')}><Cloud size={16} /><span>AWS Status</span></button><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}><Settings size={16} /><span>Settings</span></button></div></aside>; }
function Footer({ onReset }: { onReset: () => void }) { return <footer><span><ShieldCheck size={14} /> VECTOR-ONLY PRIVACY</span><span><Shield size={14} /> DERIVED SIGNALS ONLY</span><button className="demo-reset" onClick={onReset}>Reset demo</button></footer>; }
function Overview({ score, vector, connection, locked }: Props) { return <><section className="hero"><div><div className="eyebrow">CONTINUOUS BEHAVIORAL VERIFICATION</div><h1>Behavior is<br /><em>a signal.</em></h1><p className="lede">DBLA looks for meaningful changes in timing and motion.</p></div><TrustScoreGauge score={locked ? 0 : score.trust_score} tier={locked ? 'lock' : score.tier} /></section><PassiveChallenge active={score.tier === 'challenge'} /><section className="overview-grid"><BehavioralHeartbeat anomaly={score.tier !== 'silent'} /><LiveSignalPanel vector={vector} tier={locked ? 'lock' : score.tier} trust={score.trust_score} connection={connection} /><ExplainabilityPanel reasons={score.reasons} bot={score.bot_probability} /><DriftTimeline score={score.trust_score} /><div className="panel activity-panel"><div className="panel-title"><span>Recent activity</span><small>LIVE STREAM</small></div><ActivityTimeline vector={vector} /></div></section><AdminDashboard /></>; }
function Tile({ label, value, sub }: { label: string; value: string; sub: string }) { return <div className="stat-tile"><small>{label}</small><strong>{value}</strong><span>{sub}</span><i className="sparkline">⌁⌁⌁⌁</i></div>; }
function Live({ score, vector, connection, metrics, baseline }: Props) { return <><div className="page-heading"><div><div className="eyebrow">LIVE RHYTHM</div><h2>Welcome back.</h2></div><span className="status-badge">{connection === 'connected' ? 'LISTENING' : 'RECONNECTING'}</span></div><section className="panel greeting-card"><div><h3>Authenticity Score</h3><p>Behavior matches your learned profile.</p></div><TrustScoreGauge score={score.trust_score} tier={score.tier} /></section><div className="stats-row"><Tile label="Typing" value={metricValue(metrics, 'typing_wpm')} sub={metricDelta(metrics, baseline, 'typing_wpm')} /><Tile label="Mouse" value={metricValue(metrics, 'mouse_velocity_px_ms')} sub={metricDelta(metrics, baseline, 'mouse_velocity_px_ms')} /><Tile label="Scroll" value={metricValue(metrics, 'scroll_speed_px_ms')} sub={metricDelta(metrics, baseline, 'scroll_speed_px_ms')} /><Tile label="Active" value={metricValue(metrics, 'active_minutes')} sub="SESSION" /></div><ActivityTimeline vector={vector} /></>; }
function Insights({ vector, metrics, baseline }: Props) { const patterns = metrics ? patternPercentages(metrics) : null; const style = patterns ? Object.entries(patterns).sort(([, a], [, b]) => b - a)[0][0].toUpperCase() : 'COLLECTING'; return <><div className="page-heading"><div><div className="eyebrow">LIVE INSIGHTS</div><h2>Real-time analysis of your digital body language.</h2></div></div><div className="stats-row insight-stats"><Tile label="Typing WPM" value={metricValue(metrics, 'typing_wpm')} sub={metricDelta(metrics, baseline, 'typing_wpm')} /><Tile label="Mouse px/ms" value={metricValue(metrics, 'mouse_velocity_px_ms')} sub={metricDelta(metrics, baseline, 'mouse_velocity_px_ms')} /><Tile label="Scroll px/ms" value={metricValue(metrics, 'scroll_speed_px_ms')} sub={metricDelta(metrics, baseline, 'scroll_speed_px_ms')} /><Tile label="Active" value={metricValue(metrics, 'active_minutes')} sub="SESSION" /></div><div className="panel pattern-panel"><div className="panel-title"><span>Behavior pattern</span><small>{style}</small></div><div className="pattern-chips"><span>Focused {patterns?.focused ?? 0}%</span><span>Exploratory {patterns?.exploratory ?? 0}%</span><span>Idle {patterns?.idle ?? 0}%</span><span>Erratic {patterns?.erratic ?? 0}%</span></div></div><div className="panel"><div className="panel-title"><span>Last event</span><small>LIVE</small></div><ActivityTimeline vector={vector} /></div></>; }
function Fingerprint({ user, baseline, onRecalibrate }: Props) { const groups: [Behavior, string, MetricKey[]][] = [['typing', 'WPM · Flight · Dwell · Digraph', ['typing_wpm', 'key_flight_ms', 'key_dwell_ms', 'digraph_ms']], ['mouse', 'Velocity · Acceleration · Curvature', ['mouse_velocity_px_ms', 'mouse_acceleration', 'mouse_curvature']], ['scroll', 'Speed · Reversals', ['scroll_speed_px_ms', 'scroll_reversals']]]; const counts = loadCalibrationProgress(user.id).counts; return <><div className="page-heading"><div><div className="eyebrow">MY FINGERPRINT</div><h2>Your learned behavioral baseline.</h2></div><button className="outline-button" onClick={onRecalibrate}>Re-calibrate</button></div><section className="fingerprint-grid">{groups.map(([behavior, detail, keys]) => <div className="panel" key={behavior}><div className="panel-title"><span>{behavior[0].toUpperCase() + behavior.slice(1)}</span><small>{Math.min(counts[behavior], CALIBRATION_MINIMUM)}/{CALIBRATION_MINIMUM}</small></div><p>{detail}</p><div className="behavior-progress"><i><b style={{ width: `${Math.min(100, counts[behavior] / CALIBRATION_MINIMUM * 100)}%` }} /></i></div>{keys.map((key) => <div className="baseline-metric" key={key}><span>{metricLabels[key]}</span><strong>{baseline ? `${baseline[key].mean.toFixed(1)} ${metricLabels[key]} · ±${baseline[key].std.toFixed(1)}` : 'Calibration incomplete'}</strong></div>)}</div>)}</section></>; }
function Simple({ page, props }: { page: 'fingerprint' | 'aws' | 'settings'; props: Props }) { if (page === 'fingerprint') return <Fingerprint {...props} />; if (page === 'aws') return <><div className="page-heading"><div><div className="eyebrow">AWS STATUS</div><h2>Infrastructure readiness.</h2></div></div><section className="panel service-list">{['S3 training archive', 'Lambda scoring', 'API Gateway', 'CloudWatch alerts'].map((service) => <div key={service}><Cloud size={16} /><span>{service}</span><strong>NOT CONFIGURED</strong></div>)}</section></>; return <><div className="page-heading"><div><div className="eyebrow">SETTINGS</div><h2>Privacy and session controls.</h2></div></div><section className="panel"><p>Vector-only privacy. Derived signals only. No text is recorded.</p><button className="outline-button" onClick={props.onReset}>Reset demo</button></section></>; }
export function DashboardShell(props: Props) { const [page, setPage] = useState<Page>('overview'); const content = page === 'overview' ? <Overview {...props} /> : page === 'live' ? <Live {...props} /> : page === 'security' ? <Overview {...props} /> : page === 'insights' ? <Insights {...props} /> : <Simple page={page as 'fingerprint' | 'aws' | 'settings'} props={props} />; return <div className="dashboard-frame"><Header user={props.user} onLogout={props.onLogout} connection={props.connection} setPage={setPage} /><div className="dashboard-body"><Sidebar page={page} setPage={setPage} /><main className="dashboard-main">{content}<Footer onReset={props.onReset} /></main></div></div>; }
